apiVersion: v2
name: vault
description: A Helm chart with vault as subchart
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
  - name: vault
    version: v0.26.1
    repository: https://helm.releases.hashicorp.com
    alias: vault