variable "resource_group_name" {
  description = "The name of the resource group"
  type = string
}

variable "cluster_name" {
  description = "resource group prefix name"
  type = string
}

variable "location" {
  type        = string
  default     = "eastus"
  description = "Location of the resource group."
}

variable "node_count" {
  type        = number
  description = "The initial quantity of nodes for the node pool."
  default     = 3
}

variable "msi_id" {
  type        = string
  description = "The Managed Service Identity ID. Set this value if you're running this example using Managed Identity as the authentication method."
  default     = null
}

variable "username" {
  type        = string
  description = "The admin username for the new cluster."
  default     = "sgune"
}

variable "sshkey" {
  description = "holds ssh key generated by azure"
}

variable "vm_size" {
  description = "holds vm size info, found in azure docs"
  type = "string"
  
}