# certificate.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx-tls2
spec:
  secretName: nginx-tls2
  privateKey:
    rotationPolicy: Always
  commonName: hq.boopablesnoot.click
  dnsNames:
    - hq.boopablesnoot.click
  usages:
    - digital signature
    - key encipherment
    - server auth
  issuerRef:
    name: letsencrypt-azure-dns
    kind: ClusterIssuer