# certificate.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx-tls
spec:
  secretName: nginx-tls
  privateKey:
    rotationPolicy: Always
  commonName: nginx.boopablesnoot.click
  dnsNames:
    - nginx.boopablesnoot.click
  usages:
    - digital signature
    - key encipherment
    - server auth
  issuerRef:
    name: letsencrypt-azure-dns
    kind: ClusterIssuer