apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csi-secrets-store-provider-azure
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: csi-secrets-store-provider-azure
  project: default
  source:
    repoURL: 'https://github.com/shreyasgune/aks.git'
    targetRevision: 'terragrunt-setup'
    path: 'helm-stuff/argocd-managed/csi-secrets-store-provider-azure/'  # Set the path to the directory containing your manifests
    helm:
      valueFiles:
        - Values.yaml  # Add any specific values files if needed
  syncPolicy:
    automated:
      prune: true
      selfHeal: true